{
 "title": "Application Telemetry (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "flask_request_operations_total" }
   ]
  },
  {
   "title": "Model Run Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "model_run_count_total" }
   ]
  },
  {
   "title": "Model Retrain Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "model_retrain_count_total" }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Model Prediction Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(model_run_duration_seconds_bucket[30m])) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Model Retrain Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(model_retrain_duration_seconds_bucket[30m])) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_request_latency_seconds_bucket"
    }
   ]
  },
  {
   "title": "App Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(app_request_latency_seconds_bucket[10m])) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Request per Second (Python)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(flask_request_operations_total[1h])"
    }
   ]
  },
  {
   "title": "Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(model_run_duration_seconds_sum[2m]) / rate(model_run_duration_seconds_count[2m])"
    }
   ]
  }
 ]
}