FROM python:3.8.10-slim-buster

WORKDIR /app/

ADD . /app/

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc g++ git swig\
    && python3 -m pip install --upgrade pip \
    && python3 -m pip install -r requirements.txt \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge -y --auto-remove gcc g++ swig

EXPOSE 5000 5001

CMD python3 app.py 
